Reset email settings
VincentMoyo/CoolCurrency pull request #27
Opened 2021-11-15 15:53 UTC by VincentMoyo

Created reset email function
Added activity loaders

2021-11-16 04:59 UTC, bgouws requested changes
Just a small  enhancement 😄

2021-11-16 04:59 UTC, bgouws commented on CoolCurrency/Controller/SettingsViewController.swift
> +        let alert = UIAlertController(title: "Set Email",
You can also put this in an extension to make things a little more streamlined. Junaid's last PR has a good example if you want to check it out.

2021-11-17 05:07 UTC, bgouws requested changes
Just some clean up and enhancements 😄

2021-11-17 05:07 UTC, bgouws commented on CoolCurrency/CurrencyViewModel/NavigationViewModel.swift
> +                // self?.delegate?.bindViewModel()
Some commented code here?

2021-11-17 05:07 UTC, bgouws commented on CoolCurrency/CurrencyViewModel/SettingsViewModel.swift
> +                 self?.delegate?.bindViewModel()
Think there is an extra space here?

2021-11-17 05:07 UTC, bgouws commented on CoolCurrency/UserAlerts.swift
> +    static func showUpdateFirstNameAlert(for viewController: UIViewController,
So this are still a little bit too hard-coded, if I want to show a different alert I sort of need to come and add another function here, rather see if you can make one function that can handle these scenarios even if you have to pass through a few parameters 😄

2021-11-17 20:29 UTC, bgouws requested changes

2021-11-17 20:29 UTC, bgouws commented on CoolCurrency/Controller/CryptoAndMetalViewController.swift
> +        currencyPicker.setValue(UIColor(named: "SecondaryNavy"), forKeyPath: "textColor")
You can add this to your style kit 😄 also consider the naming convention I have used below:

```
static var secondaryColour: UIColor {
   return UIColor(named: "secondaryColour")
}

2021-11-17 20:29 UTC, bgouws commented on CoolCurrency/Controller/HomeCurrencyViewController.swift
> +        currencyPickerView.setValue(UIColor(named: "SecondaryNavy"), forKeyPath: "textColor")
Style kit

2021-11-18 17:09 UTC, bgouws approved these changes

2021-11-18 17:48 UTC, AbdullahNanaDVT approved these changes

2021-11-18 18:12 UTC, merged